#!/bin/sh
  LOG_JSON_DATE=$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")
  LOG_JSON_TYPE=$(echo "${1}" | awk 'BEGIN { getline; print toupper($0) }')
  echo "{\"time\":\"${LOG_JSON_DATE}\", \"type\":\"${LOG_JSON_TYPE}\", \"message\":\"${2}\"}"